sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install -y libgl1-mesa-dev libpulse-dev libxrandr-dev libgtk-3-dev

script:
  - make linux-debug64       && ./build/linux64/bin/crown-debug --run-unit-tests
  - make linux-development64 && ./build/linux64/bin/crown-development --run-unit-tests
  - make linux-release64     && ./build/linux64/bin/crown-release --run-unit-tests

notifications:
  email: false
